const spsLiteActions = {
    'api::modal.modal': ['find'],
    'api::not-found-page.not-found-page': ['find'],
    'api::slider.slider': ['find'],
    'api::main-page.main-page': ['find'],
    'api::theme.theme': ['find'],
    'api::form.form': ['find'],
    'api::form-request.form-request': ['create'],
    'api::review.review': ['find'],
    'api::tier.tier': ['find'],
    'api::currency.currency': ['find'],
    'api::slide-over.slide-over': ['find'],
    'api::sidebar.sidebar': ['find'],
    'api::topbar.topbar': ['find'],
    'api::navbar.navbar': ['find'],
    'api::footer.footer': ['find'],
    'api::layout.layout': ['find'],
    'api::metatag.metatag': ['find'],
    'api::page.page': ['find', 'findOne'],
};

module.exports = () => ({
    authenticated: {
        role: 1,
        actions: {
            ...spsLiteActions,
            'plugin::content-type-builder.components': [],
            'plugin::content-type-builder.content-types': [],
            'plugin::email.email': [],
            'plugin::i18n.locales': [],
            'plugin::users-permissions.auth': [],
            'plugin::users-permissions.user': [],
            'plugin::users-permissions.role': [],
            'plugin::users-permissions.permission': [],
            'plugin::upload.content-api': [],
        },
    },
    public: {
        role: 2,
        actions: {
            ...spsLiteActions,
            'plugin::content-type-builder.components': [],
            'plugin::content-type-builder.content-types': [],
            'plugin::email.email': [],
            'plugin::upload.content-api': [],
            'plugin::i18n.locales': [],
            'plugin::users-permissions.auth': [],
            'plugin::users-permissions.user': [],
            'plugin::users-permissions.role': [],
            'plugin::users-permissions.permissiosn': [],
        },
    },
});
