CREATE TABLE IF NOT EXISTS "sps_h_metadata" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"variant" text DEFAULT 'default' NOT NULL,
	"title" text,
	"description" text,
	"keywords" text,
	"author" text,
	"viewport" text,
	"opengraph_title" text,
	"opengraph_description" text,
	"opengraph_url" text,
	"opengraph_type" text,
	"opengraph_site_name" text,
	"opengraph_locale" text,
	"twitter_card" text,
	"twitter_site" text,
	"twitter_creator" text,
	"twitter_title" text,
	"twitter_description" text,
	"twitter_url" text,
	"twitter_domain" text,
	"twitter_app_country" text
);
