GET http://localhost:3000/api/sps-website-builder/buttons?filters[and][0][column]=title&filters[and][0][method]=ilike&filters[and][0][value]=%ain%&filters[and][1][column]=variant&filters[and][1][method]=eq&filters[and][1][value]=link HTTP/1.1
content-type: application/json