FROM postgres:latest

# Moving dashboard-backend database
# COPY ./sps.sql /docker-entrypoint-initdb.d/sps.sql
# Auto increment script
# COPY ./sps_ai.sql sps_ai.sql

# Grant premissions to file and start dump restore
# RUN chown postgres:postgres /docker-entrypoint-initdb.d/sps.sql

# CMD ["docker-entrypoint.sh", "postgres"]