export { Table as SPSHLayoutsToWidgets } from "@sps/sps-host/relations/layouts-to-widgets/backend/repository/database";
export { Table as SPSHWidgetsToExternalModules } from "@sps/sps-host/relations/widgets-to-external-widgets/backend/repository/database";
export { Table as SPSHPagesToWidgets } from "@sps/sps-host/relations/pages-to-widgets/backend/repository/database";
export { Table as SPSHPagesToMetadata } from "@sps/sps-host/relations/pages-to-metadata/backend/repository/database";
export { Table as SPSHPagesToLayouts } from "@sps/sps-host/relations/pages-to-layouts/backend/repository/database";
export { Table as SPSHMetadata } from "@sps/sps-host/models/metadata/backend/repository/database";
export { Table as SPSHLayout } from "@sps/sps-host/models/layout/backend/repository/database";
export { Table as SPSHPage } from "@sps/sps-host/models/page/backend/repository/database";
export { Table as SPSHWidget } from "@sps/sps-host/models/widget/backend/repository/database";
export {};
