/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import i18N from "@strapi/plugin-i18n/strapi-admin";
import sentry from "@strapi/plugin-sentry/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import countrySelect from "strapi-plugin-country-select/strapi-admin";
import emailDesigner from "strapi-plugin-email-designer/strapi-admin";
import spsBilling from "../../src/plugins/sps-billing/strapi-admin";
import spsCrm from "../../src/plugins/sps-crm/strapi-admin";
import spsNotification from "../../src/plugins/sps-notification/strapi-admin";
import spsWebsiteBuilder from "../../src/plugins/sps-website-builder/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    i18n: i18N,
    sentry: sentry,
    "users-permissions": usersPermissions,
    "country-select": countrySelect,
    "email-designer": emailDesigner,
    "sps-billing": spsBilling,
    "sps-crm": spsCrm,
    "sps-notification": spsNotification,
    "sps-website-builder": spsWebsiteBuilder,
  },
});
