---
- name: Fill Postgres secrets in GitHub
  hosts: all
  become: yes
  vars:
    - github_token: "{{ GITHUB_TOKEN }}"
    - github_repository: "{{ GITHUB_REPOSITORY }}"
  tasks:
    - name: Delete artifacts
      file:
        path: /home/code/github-node-api/
        state: absent

    - name: Create github-node-api directory
      file:
        path: "/home/code/github-node-api"
        state: directory

    - name: Fill github-node-api directory from local
      copy:
        src: "{{ playbook_dir }}/../github/github-node-api/{{ item }}"
        dest: "/home/code/github-node-api/{{ item }}"
      loop:
        - create_secret.js
        - package.json

    - name: Install dependencies
      shell:
        cmd: "npm install"
        chdir: "/home/code/github-node-api"

    - name: Set secrets to GitHub
      no_log: true
      shell:
        cmd: "node ./create_secret.js {{ github_token }} {{ github_repository }} {{ item.secret_name }} {{ item.secret_content }} {{ item.secret_scope }}"
        chdir: "/home/code/github-node-api"
      loop:
        - {
            secret_name: DATABASE_HOST,
            secret_content: "{{ inventory_hostname }}",
            secret_scope: actions,
          }

    - name: Delete artifacts
      file:
        path: /home/code/github-node-api/
        state: absent
