export { GoogleTagManager } from "./lib/scripts/google-tag-manager";
export { rtkQueryErrorLogger } from "./lib/redux/rtk-query-error-logger";
export { rootSlices } from "./lib/redux/apps";
export * as page from "./lib/app/[locale]/[[...url]]/page";
export * as robots from "./lib/app/robots.txt/route";
export * as sitemap from "./lib/app/sitemap.xml/route";
export * as globalError from "./lib/app/global-error";
export * as notFound from "./lib/app/not-found";
export { RootLayout } from "./lib/app/root-layout";
export * from "./lib/redux/slices";
// export { Component as Footer } from "./lib/entities/footer/component";
// export { Component as Modal } from "./lib/entities/modal/component";
export { pageBlockComponents } from "./lib/models/_aliases";
// export { PageBlocks } from "./lib/components/page-blocks";
// export { Component as SlideOver } from "./lib/entities/slide-over/component";
// export { Component as Loader } from "./lib/entities/loader/component";
// export { Component as Layout } from "./lib/entities/layout/component";
// export { Component as Topbar } from "./lib/entities/topbar/component";
// export { Component as Sidebar } from "./lib/entities/sidebar/component";
// export { Component as Flyout } from "./lib/entities/flyout/component";
// export { Component as Navbar } from "./lib/entities/navbar/component";
// export { Component as Button } from "./lib/components/elements/button/component";
export { ReduxProvider } from "./lib/redux";
