import * as pgCore from "drizzle-orm/pg-core";

export const fields = {
  id: pgCore.uuid("id").primaryKey().defaultRandom(),
  createdAt: pgCore.timestamp("created_at").notNull().defaultNow(),
  updatedAt: pgCore.timestamp("updated_at").notNull().defaultNow(),
  variant: pgCore.text("variant").notNull().default("default"),
  title: pgCore.text("title"),
  description: pgCore.text("description"),
  keywords: pgCore.text("keywords"),
  author: pgCore.text("author"),
  viewport: pgCore.text("viewport"),
  opengraphTitle: pgCore.text("opengraph_title"),
  opengraphDescription: pgCore.text("opengraph_description"),
  opengraphUrl: pgCore.text("opengraph_url"),
  opengraphType: pgCore.text("opengraph_type"),
  opengraphSiteName: pgCore.text("opengraph_site_name"),
  opengraphLocale: pgCore.text("opengraph_locale"),
  twitterCard: pgCore.text("twitter_card"),
  twitterSite: pgCore.text("twitter_site"),
  twitterCreator: pgCore.text("twitter_creator"),
  twitterTitle: pgCore.text("twitter_title"),
  twitterDescription: pgCore.text("twitter_description"),
  twitterUrl: pgCore.text("twitter_url"),
  twitterDomain: pgCore.text("twitter_domain"),
  twitterAppCountry: pgCore.text("twitter_app_country"),
};
