#!/bin/bash
. ./get_env.sh

DOMAIN=$(get_env DOMAIN)
PORTAINER_USERNAME=$(get_env PORTAINER_USERNAME)
PORTAINER_PASSWORD=$(get_env PORTAINER_PASSWORD)
DOCKER_HUB_USERNAME=$(get_env DOCKER_HUB_USERNAME)
DOCKER_HUB_PASSWORD=$(get_env DOCKER_HUB_PASSWORD)
DOCKER_HUB_URL=$(get_env DOCKER_HUB_URL)
DOCKER_HUB_LOGIN_USERNAME=$(get_env DOCKER_HUB_LOGIN_USERNAME)
PORTAINER_SERVICE_SUBDOMAIN=$(get_env PORTAINER_SERVICE_SUBDOMAIN)

PORTAINER_URL=$PORTAINER_SERVICE_SUBDOMAIN.$DOMAIN

ansible-playbook create_portainer_user.yaml add_docker_hub_registry.yaml \
    -e "DOMAIN=$DOMAIN \
        PORTAINER_URL=$PORTAINER_URL \
        PORTAINER_USERNAME=$PORTAINER_USERNAME \
        PORTAINER_PASSWORD=$PORTAINER_PASSWORD \
        DOCKER_HUB_USERNAME=$DOCKER_HUB_USERNAME \
        DOCKER_HUB_PASSWORD=$DOCKER_HUB_PASSWORD \
        DOCKER_HUB_URL=$DOCKER_HUB_URL \
        DOCKER_HUB_LOGIN_USERNAME=$DOCKER_HUB_LOGIN_USERNAME"