#!/bin/bash
. ./get_env.sh

DOMAIN=$(get_env DOMAIN)
SERVICE_NAME=$(get_env DOCUMENTATION_SERVICE_NAME)
SERVICE_SUBDOMAIN=$(get_env DOCUMENTATION_SERVICE_SUBDOMAIN)
DOCKER_HUB_SERVICE_REPOSITORY=$(get_env DOCUMENTATION_DOCKER_HUB_REPOSITORY_NAME)
SERVICE_SUBDOMAIN=$(get_env DOCUMENTATION_SERVICE_SUBDOMAIN)
DOCKER_HUB_USERNAME=$(get_env DOCKER_HUB_USERNAME)
DOCKER_HUB_PASSWORD=$(get_env DOCKER_HUB_PASSWORD)
PORTAINER_USERNAME=$(get_env PORTAINER_USERNAME)
PORTAINER_PASSWORD=$(get_env PORTAINER_PASSWORD)
BACKEND_SERVICE_SUBDOMAIN=$(get_env BACKEND_SERVICE_SUBDOMAIN)
PORTAINER_SERVICE_SUBDOMAIN=$(get_env PORTAINER_SERVICE_SUBDOMAIN)

PORTAINER_URL=$PORTAINER_SERVICE_SUBDOMAIN.$DOMAIN

if [ -z "$SERVICE_SUBDOMAIN" ]
then
    SERVICE_URL=$DOMAIN
else 
    SERVICE_URL=$SERVICE_SUBDOMAIN.$DOMAIN
fi

if [ "$1" == "up" ]
then
    ansible-playbook create_documentation.yaml \
        -e "DOMAIN=$DOMAIN \
            SERVICE_NAME=$SERVICE_NAME \
            SERVICE_URL=$SERVICE_URL \
            PORTAINER_URL=$PORTAINER_URL \
            DOCKER_HUB_SERVICE_REPOSITORY=$DOCKER_HUB_SERVICE_REPOSITORY \
            DOCKER_HUB_USERNAME=$DOCKER_HUB_USERNAME \
            DOCKER_HUB_PASSWORD=$DOCKER_HUB_PASSWORD \
            PORTAINER_USERNAME=$PORTAINER_USERNAME \
            PORTAINER_PASSWORD=$PORTAINER_PASSWORD"
else
    ansible-playbook delete_documentation.yaml \
        -e "SERVICE_NAME=$SERVICE_NAME"
fi