#!/bin/bash
. ./get_env.sh

DOMAIN=$(get_env DOMAIN)
GITHUB_TOKEN=$(get_env GITHUB_TOKEN)
GITHUB_REPOSITORY=$(get_env GITHUB_REPOSITORY)
PROJECT_NAME=$(get_env PROJECT_NAME)
DOCKER_HUB_USERNAME=$(get_env DOCKER_HUB_USERNAME)
DOCKER_HUB_PASSWORD=$(get_env DOCKER_HUB_PASSWORD)
DOCKER_HUB_URL=$(get_env DOCKER_HUB_URL)
DOCKER_HUB_LOGIN_USERNAME=$(get_env DOCKER_HUB_LOGIN_USERNAME)
BACKEND_SERVICE_SUBDOMAIN=$(get_env BACKEND_SERVICE_SUBDOMAIN)
FRONTEND_SERVICE_SUBDOMAIN=$(get_env FRONTEND_SERVICE_SUBDOMAIN)
DATABASE_NAME=$(get_env POSTGRES_DB)
DATABASE_PASSWORD=$(get_env POSTGRES_PASSWORD)
DATABASE_USERNAME=$(get_env POSTGRES_USER)
DOCKER_HUB_PASSWORD=$(get_env DOCKER_HUB_PASSWORD)
AWS_S3_REGION=$(get_env AWS_S3_REGION)
PORTAINER_SERVICE_SUBDOMAIN=$(get_env PORTAINER_SERVICE_SUBDOMAIN)

PORTAINER_URL=$PORTAINER_SERVICE_SUBDOMAIN.$DOMAIN

if [ -z "$BACKEND_SERVICE_SUBDOMAIN" ]
then
    BACKEND_URL=$DOMAIN
else
    BACKEND_URL=$BACKEND_SERVICE_SUBDOMAIN.$DOMAIN
fi


if [ -z "$FRONTEND_SERVICE_SUBDOMAIN" ]
then
    FRONTEND_URL=$DOMAIN
else 
    FRONTEND_URL=$FRONTEND_SERVICE_SUBDOMAIN.$DOMAIN
fi

if [ "$1" == "up" ]
then
    ansible-playbook fill_github.yaml delete_ansible_secrets_from_github.yaml \
        -e "GITHUB_TOKEN=$GITHUB_TOKEN \
            GITHUB_REPOSITORY=$GITHUB_REPOSITORY \
            PROJECT_NAME=$PROJECT_NAME \
            DOCKER_HUB_USERNAME=$DOCKER_HUB_USERNAME \
            DOCKER_HUB_PASSWORD=$DOCKER_HUB_PASSWORD \
            DOCKER_HUB_URL=$DOCKER_HUB_URL \
            DOCKER_HUB_LOGIN_USERNAME=$DOCKER_HUB_LOGIN_USERNAME \
            BACKEND_URL=$BACKEND_URL \
            FRONTEND_URL=$FRONTEND_URL \
            DATABASE_NAME=$DATABASE_NAME \
            DATABASE_PASSWORD=$DATABASE_PASSWORD \
            DATABASE_USERNAME=$DATABASE_USERNAME \
            PORTAINER_URL=$PORTAINER_URL \
            AWS_S3_REGION=$AWS_S3_REGION"
else
    ansible-playbook clear_github.yaml delete_ansible_secrets_from_github.yaml \
        -e "GITHUB_TOKEN=$GITHUB_TOKEN \
            GITHUB_REPOSITORY=$GITHUB_REPOSITORY \
            PROJECT_NAME=$PROJECT_NAME \
            DOCKER_HUB_USERNAME=$DOCKER_HUB_USERNAME \
            DOCKER_HUB_PASSWORD=$DOCKER_HUB_PASSWORD \
            DOCKER_HUB_URL=$DOCKER_HUB_URL \
            DOCKER_HUB_LOGIN_USERNAME=$DOCKER_HUB_LOGIN_USERNAME \
            BACKEND_URL=$BACKEND_URL \
            FRONTEND_URL=$FRONTEND_URL \
            DATABASE_NAME=$DATABASE_NAME \
            DATABASE_PASSWORD=$DATABASE_PASSWORD \
            DATABASE_USERNAME=$DATABASE_USERNAME \
            PORTAINER_URL=$PORTAINER_URL \
            AWS_S3_REGION=$AWS_S3_REGION"
fi